---

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel_arguments: diskencrypt=false release=dev ubuntuversion=bionic arch=amd64 username=azureiot password=azureiot azurescopeid=0ne001927B6
